# TTA Optimized Vector Addition Benchmark

# Element 0
MOVE_IMM valA0, LSU_ADDR
MOVE LSU_RDATA, ADD_IN1
MOVE_IMM valB0, LSU_ADDR
MOVE LSU_RDATA, ADD_IN2
MOVE_IMM valC0, LSU_ADDR
MOVE ADD_OUT, LSU_WDATA

# Element 1
MOVE_IMM valA1, LSU_ADDR
MOVE LSU_RDATA, ADD_IN1
MOVE_IMM valB1, LSU_ADDR
MOVE LSU_RDATA, ADD_IN2
MOVE_IMM valC1, LSU_ADDR
MOVE ADD_OUT, LSU_WDATA

# Element 2
MOVE_IMM valA2, LSU_ADDR
MOVE LSU_RDATA, ADD_IN1
MOVE_IMM valB2, LSU_ADDR
MOVE LSU_RDATA, ADD_IN2
MOVE_IMM valC2, LSU_ADDR
MOVE ADD_OUT, LSU_WDATA

# Element 3
MOVE_IMM valA3, LSU_ADDR
MOVE LSU_RDATA, ADD_IN1
MOVE_IMM valB3, LSU_ADDR
MOVE LSU_RDATA, ADD_IN2
MOVE_IMM valC3, LSU_ADDR
MOVE ADD_OUT, LSU_WDATA

HALT

ORG 40
valA0: DATA 10
valA1: DATA 20
valA2: DATA 30
valA3: DATA 40

valB0: DATA 1
valB1: DATA 2
valB2: DATA 3
valB3: DATA 4

valC0: DATA 0
valC1: DATA 0
valC2: DATA 0
valC3: DATA 0
